"""
Training Pipeline for G-NeSAI

This module provides a complete training pipeline integrating all components:
- Data generation and loading
- Perception model training
- Cognitive agent training
- Neuro-symbolic integration
- Evaluation and visualization
- Experiment tracking
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
from pathlib import Path
import json
from datetime import datetime
import logging

# Import project modules
from data_factory.generator import SignalGenerator
from data_factory.spectrum_loader import create_train_val_loaders
from perception_layer.complex_net import ComplexValuedCNN, train_cvnn
from cognitive_core import ActiveInferenceAgent, CognitiveController
from cognitive_core.symbolic_rules import SymbolicRuleEngine, NeuroSymbolicIntegrator

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class ExperimentTracker:
    """Tracks experiment metrics and results."""

    def __init__(self, experiment_name: str, save_dir: str = "experiments"):
        self.experiment_name = experiment_name
        self.save_dir = Path(save_dir) / experiment_name
        self.save_dir.mkdir(parents=True, exist_ok=True)

        self.metrics = {
            'train_loss': [],
            'val_loss': [],
            'train_acc': [],
            'val_acc': [],
            'free_energy': [],
            'symbolic_compliance': []
        }

        self.start_time = datetime.now()

    def log_metrics(self, epoch: int, **kwargs):
        """Log metrics for the current epoch."""
        for key, value in kwargs.items():
            if key in self.metrics:
                self.metrics[key].append(value)

        # Save metrics to file
        with open(self.save_dir / 'metrics.json', 'w') as f:
            json.dump(self.metrics, f, indent=2)

    def save_model(self, model, name: str):
        """Save model checkpoint."""
        torch.save(model.state_dict(), self.save_dir / f'{name}.pth')

    def save_plot(self, plot_func, name: str):
        """Save a plot generated by a function."""
        plt.figure(figsize=(10, 6))
        plot_func()
        plt.savefig(self.save_dir / f'{name}.png', dpi=300, bbox_inches='tight')
        plt.close()

    def finalize(self):
        """Finalize experiment and save summary."""
        end_time = datetime.now()
        duration = end_time - self.start_time

        summary = {
            'experiment_name': self.experiment_name,
            'start_time': self.start_time.isoformat(),
            'end_time': end_time.isoformat(),
            'duration_seconds': duration.total_seconds(),
            'final_metrics': {k: v[-1] if v else None for k, v in self.metrics.items()}
        }

        with open(self.save_dir / 'summary.json', 'w') as f:
            json.dump(summary, f, indent=2)

class GNeSAITrainer:
    """
    Complete training pipeline for G-NeSAI system.
    """

    def __init__(self, config: dict):
        """
        Initialize the trainer with configuration.

        Args:
            config: Training configuration dictionary
        """
        self.config = config
        self.device = torch.device(config.get('device', 'cuda' if torch.cuda.is_available() else 'cpu'))

        # Reproducibility: set seeds if provided
        seed = config.get('seed', None)
        if seed is not None:
            random.seed(seed)
            np.random.seed(seed)
            torch.manual_seed(seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(seed)
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False

        # Initialize components
        # If a seed is provided in config, pass it to the signal generator for reproducibility
        seed = config.get('seed', None)
        self.signal_generator = SignalGenerator(seed=seed)
        self.perception_model = ComplexValuedCNN().to(self.device)
        self.cognitive_controller = CognitiveController()
        self.symbolic_engine = SymbolicRuleEngine()
        self.neuro_symbolic_integrator = NeuroSymbolicIntegrator(
            self.cognitive_controller.agent, self.symbolic_engine
        )

        # Initialize experiment tracker
        self.tracker = ExperimentTracker(config.get('experiment_name', 'gnesai_training'))

        # Training parameters
        self.num_epochs = config.get('num_epochs', 100)
        self.batch_size = config.get('batch_size', 32)
        self.learning_rate = config.get('learning_rate', 5e-4)
        self.clip_grad_norm = config.get('clip_grad_norm', 5.0)

        # Optimizers
        self.perception_optimizer = optim.Adam(self.perception_model.parameters(), lr=self.learning_rate)
        self.perception_criterion = nn.CrossEntropyLoss()

    def generate_training_data(self, num_samples: int = 10000):
        """
        Generate synthetic training data.

        Args:
            num_samples: Number of training samples to generate
        """
        logger.info(f"Generating {num_samples} training samples...")

        # Generate data
        train_data, train_labels, _ = self.signal_generator.generate_training_data(num_samples)

        # Save to HDF5
        import h5py
        with h5py.File(self.tracker.save_dir / 'training_data.h5', 'w') as f:
            f.create_dataset('signals', data=train_data)
            f.create_dataset('labels', data=train_labels)

        logger.info("Training data saved.")
        return train_data, train_labels

    def train_perception_model(self, train_loader, val_loader):
        """
        Train the perception (CVNN) model.

        Args:
            train_loader: Training data loader
            val_loader: Validation data loader
        """
        logger.info("Training perception model...")

        best_val_acc = 0.0

        for epoch in range(self.num_epochs):
            # Training phase
            self.perception_model.train()
            train_loss = 0.0
            train_correct = 0
            train_total = 0

            for signals, labels in train_loader:
                signals, labels = signals.to(self.device), labels.to(self.device)

                self.perception_optimizer.zero_grad()
                outputs = self.perception_model(signals)
                loss = self.perception_criterion(outputs, labels)
                loss.backward()
                # gradient clipping to stabilize training
                torch.nn.utils.clip_grad_norm_(self.perception_model.parameters(), self.clip_grad_norm)
                self.perception_optimizer.step()

                train_loss += loss.item()
                _, predicted = outputs.max(1)
                train_total += labels.size(0)
                train_correct += predicted.eq(labels).sum().item()

            train_loss /= len(train_loader)
            train_acc = 100. * train_correct / train_total

            # Validation phase
            val_loss, val_acc = self._validate_perception_model(val_loader)

            # Log metrics
            self.tracker.log_metrics(
                epoch=epoch,
                train_loss=train_loss,
                val_loss=val_loss,
                train_acc=train_acc,
                val_acc=val_acc
            )

            logger.info(f"Epoch {epoch+1}/{self.num_epochs}: "
                       f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}%, "
                       f"Val Loss: {val_loss:.4f}, Val Acc: {val_acc:.2f}%")

            # Save best model
            if val_acc > best_val_acc:
                best_val_acc = val_acc
                self.tracker.save_model(self.perception_model, 'best_perception_model')

        # Save final model
        self.tracker.save_model(self.perception_model, 'final_perception_model')

    def _validate_perception_model(self, val_loader):
        """Validate the perception model."""
        self.perception_model.eval()
        val_loss = 0.0
        val_correct = 0
        val_total = 0

        with torch.no_grad():
            for signals, labels in val_loader:
                signals, labels = signals.to(self.device), labels.to(self.device)
                outputs = self.perception_model(signals)
                loss = self.perception_criterion(outputs, labels)

                val_loss += loss.item()
                _, predicted = outputs.max(1)
                val_total += labels.size(0)
                val_correct += predicted.eq(labels).sum().item()

        val_loss /= len(val_loader)
        val_acc = 100. * val_correct / val_total

        return val_loss, val_acc

    def train_cognitive_agent(self, train_data, num_episodes: int = 100):
        """
        Train the cognitive agent using Active Inference.

        Args:
            train_data: Training data (signals, labels)
            num_episodes: Number of training episodes
        """
        logger.info("Training cognitive agent...")

        signals, labels = train_data

        for episode in range(num_episodes):
            episode_free_energy = []
            episode_rewards = []

            for i, (signal, label) in enumerate(zip(signals, labels)):
                # Process signal through cognitive controller
                action, free_energy, beliefs = self.cognitive_controller.process_signal(signal)

                # Calculate reward (higher for correct actions)
                reward = 1.0 if action == label else -1.0
                episode_rewards.append(reward)
                episode_free_energy.append(free_energy)

                # Learning step
                self.cognitive_controller.agent.learn(label, action, reward)

                if i % 100 == 0:
                    logger.info(f"Episode {episode+1}, Sample {i+1}: Action {action}, Reward {reward:.2f}")

            # Log episode metrics
            avg_free_energy = np.mean(episode_free_energy)
            avg_reward = np.mean(episode_rewards)

            self.tracker.log_metrics(
                epoch=episode,
                free_energy=avg_free_energy,
                train_acc=avg_reward * 50 + 50  # Convert to percentage
            )

            logger.info(f"Episode {episode+1}/{num_episodes}: "
                       f"Avg Free Energy: {avg_free_energy:.4f}, Avg Reward: {avg_reward:.4f}")

    def evaluate_system(self, test_data):
        """
        Evaluate the complete G-NeSAI system.

        Args:
            test_data: Test data (signals, labels)
        """
        logger.info("Evaluating complete system...")

        signals, labels = test_data
        predictions = []
        free_energies = []
        symbolic_compliances = []

        for signal, true_label in zip(signals, labels):
            # Get neural prediction
            action, free_energy, beliefs = self.cognitive_controller.process_signal(signal)

            # Get symbolic context (mock for evaluation)
            context = {
                'threat_level': 2,  # High threat
                'mission_criticality': 0.8,
                'friendly_forces_present': False
            }

            # Neuro-symbolic decision
            final_action, decision_info = self.neuro_symbolic_integrator.hybrid_decision(
                torch.tensor([action], dtype=torch.float32), context
            )

            predictions.append(final_action.value)
            free_energies.append(free_energy)
            symbolic_compliances.append(1.0 if final_action.value == action else 0.0)

        # Calculate metrics
        predictions = np.array(predictions)
        labels = np.array(labels)

        accuracy = np.mean(predictions == labels)
        avg_free_energy = np.mean(free_energies)
        symbolic_compliance_rate = np.mean(symbolic_compliances)

        # Classification report
        report = classification_report(labels, predictions, output_dict=True)

        # Confusion matrix
        cm = confusion_matrix(labels, predictions)

        # Save results
        results = {
            'accuracy': accuracy,
            'avg_free_energy': avg_free_energy,
            'symbolic_compliance_rate': symbolic_compliance_rate,
            'classification_report': report,
            'confusion_matrix': cm.tolist()
        }

        with open(self.tracker.save_dir / 'evaluation_results.json', 'w') as f:
            json.dump(results, f, indent=2)

        logger.info(f"Evaluation Results:")
        logger.info(f"Accuracy: {accuracy:.4f}")
        logger.info(f"Avg Free Energy: {avg_free_energy:.4f}")
        logger.info(f"Symbolic Compliance Rate: {symbolic_compliance_rate:.4f}")

        return results

    def create_visualizations(self):
        """Create and save visualizations of training results."""
        logger.info("Creating visualizations...")

        # Free Energy plot
        def plot_free_energy():
            plt.plot(self.tracker.metrics['free_energy'])
            plt.title('Free Energy During Training')
            plt.xlabel('Episode')
            plt.ylabel('Free Energy')
            plt.grid(True)

        self.tracker.save_plot(plot_free_energy, 'free_energy_training')

        # Accuracy plot
        def plot_accuracy():
            plt.plot(self.tracker.metrics['train_acc'], label='Train')
            plt.plot(self.tracker.metrics['val_acc'], label='Validation')
            plt.title('Model Accuracy During Training')
            plt.xlabel('Epoch')
            plt.ylabel('Accuracy (%)')
            plt.legend()
            plt.grid(True)

        self.tracker.save_plot(plot_accuracy, 'accuracy_training')

        # Loss plot
        def plot_loss():
            plt.plot(self.tracker.metrics['train_loss'], label='Train')
            plt.plot(self.tracker.metrics['val_loss'], label='Validation')
            plt.title('Model Loss During Training')
            plt.xlabel('Epoch')
            plt.ylabel('Loss')
            plt.legend()
            plt.grid(True)

        self.tracker.save_plot(plot_loss, 'loss_training')

    def run_full_training_pipeline(self):
        """Run the complete training pipeline."""
        logger.info("Starting full G-NeSAI training pipeline...")

        try:
            # Step 1: Generate training data
            train_data, train_labels = self.generate_training_data(5000)
            val_data, val_labels = self.generate_training_data(1000)

            # Step 2: Create data loaders
            # Create loaders with the global seed to ensure deterministic splits and shuffling
            train_loader, val_loader = create_train_val_loaders(
                train_data, train_labels,
                val_split=0.2,
                batch_size=self.batch_size,
                augment_train=True,
                seed=seed if seed is not None else 42,
                loader_seed=(seed if seed is not None else 42)
            )

            # Step 3: Train perception model
            self.train_perception_model(train_loader, val_loader)

            # Step 4: Train cognitive agent
            self.train_cognitive_agent((train_data, train_labels), num_episodes=50)

            # Step 5: Generate test data and evaluate
            test_data, test_labels = self.generate_training_data(1000)
            results = self.evaluate_system((test_data, test_labels))

            # Step 6: Create visualizations
            self.create_visualizations()

            # Step 7: Finalize experiment
            self.tracker.finalize()

            logger.info("Training pipeline completed successfully!")
            return results

        except Exception as e:
            logger.error(f"Training pipeline failed: {e}")
            raise

def create_default_config():
    """Create default training configuration."""
    return {
        'experiment_name': f'gnesai_training_{datetime.now().strftime("%Y%m%d_%H%M%S")}',
        'num_epochs': 50,
        'batch_size': 32,
        'learning_rate': 5e-4,
        'seed': 42,
        'clip_grad_norm': 5.0,
        'device': 'cuda' if torch.cuda.is_available() else 'cpu'
    }

if __name__ == "__main__":
    # Run training pipeline
    config = create_default_config()
    trainer = GNeSAITrainer(config)
    results = trainer.run_full_training_pipeline()

    print("Training completed!")
    print(f"Final accuracy: {results['accuracy']:.4f}")
    print(f"Results saved in: {trainer.tracker.save_dir}")